/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class BP4_NN_IO_t implements lcm.lcm.LCMEncodable
{
    public float input[];
    public float output[];
 
    public BP4_NN_IO_t()
    {
        input = new float[35];
        output = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2eb76ea00481d757L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.BP4_NN_IO_t.class))
            return 0L;
 
        classes.add(lcmtypes.BP4_NN_IO_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 35; a++) {
            outs.writeFloat(this.input[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.output[a]); 
        }
 
    }
 
    public BP4_NN_IO_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public BP4_NN_IO_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.BP4_NN_IO_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.BP4_NN_IO_t o = new lcmtypes.BP4_NN_IO_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.input = new float[(int) 35];
        for (int a = 0; a < 35; a++) {
            this.input[a] = ins.readFloat();
        }
 
        this.output = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.output[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.BP4_NN_IO_t copy()
    {
        lcmtypes.BP4_NN_IO_t outobj = new lcmtypes.BP4_NN_IO_t();
        outobj.input = new float[(int) 35];
        System.arraycopy(this.input, 0, outobj.input, 0, 35); 
        outobj.output = new float[(int) 12];
        System.arraycopy(this.output, 0, outobj.output, 0, 12); 
        return outobj;
    }
 
}

