/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class contact_t implements lcm.lcm.LCMEncodable
{
    public double contact[];
 
    public contact_t()
    {
        contact = new double[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x526c2944c92a57d0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.contact_t.class))
            return 0L;
 
        classes.add(lcmtypes.contact_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.contact[a]); 
        }
 
    }
 
    public contact_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public contact_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.contact_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.contact_t o = new lcmtypes.contact_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.contact = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.contact[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.contact_t copy()
    {
        lcmtypes.contact_t outobj = new lcmtypes.contact_t();
        outobj.contact = new double[(int) 4];
        System.arraycopy(this.contact, 0, outobj.contact, 0, 4); 
        return outobj;
    }
 
}

