"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class NN_IO_t(object):
    __slots__ = ["input", "output"]

    def __init__(self):
        self.input = [ 0.0 for dim0 in range(50) ]
        self.output = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(NN_IO_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>50f', *self.input[:50]))
        buf.write(struct.pack('>12f', *self.output[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != NN_IO_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return NN_IO_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = NN_IO_t()
        self.input = struct.unpack('>50f', buf.read(200))
        self.output = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if NN_IO_t in parents: return 0
        tmphash = (0x2eb76ea00c6dd757) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if NN_IO_t._packed_fingerprint is None:
            NN_IO_t._packed_fingerprint = struct.pack(">Q", NN_IO_t._get_hash_recursive([]))
        return NN_IO_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

